#!/bin/bash
export LANG=C.UTF-8

if ! git diff-index --quiet HEAD --; then
  echo "Directory contains modifications, cannot proceed." >&2
  exit 1
fi

workdir=$(mktemp -d "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")

repo_basename=$(basename "$PWD")
repo_basename=${repo_basename%.git}

for h in $(git log --format=format:"%H"); do
  specfile=$workdir/$h.spec

  git show $h:$repo_basename.spec > $specfile
  sed -i '/%changelog/,$d' $specfile
  version_release=$(rpmspec -q --undefine dist --queryformat '[%|epoch?{%{epoch}:}|%{version}-%{release}\n]' $specfile 2> /dev/null | head -1)

  git log $h -1 --date=format:"%a %b %d %Y" --format=format:"* %ad %cn <%ce> - $version_release%n- %s%n%n"
done

git reset --hard 2>&1 > /dev/null

rm -rf $workdir
